### ISSUE TITLE
where is the pbmc10k_garnett_results.txt file?

### ISSUE THREAD

**Issue by vagabond12** [aertslab/SCENICprotocol#12]
where is the pbmc10k_garnett_results.txt file? Thank you very much.

**Comment by vagabond12** [comment]
where could we download this file?

**Comment by vagabond12** [comment]
![image](https://user-images.githubusercontent.com/24886447/81698450-93924d00-9498-11ea-9c1f-c4ec48e0c255.png)

**Comment by cflerin** [comment]
I've uploaded the Garnett classifications [here](https://github.com/aertslab/SCENICprotocol/blob/master/notebooks/pbmc10k_garnett_results.txt).
