### ISSUE TITLE
pyscenic ctx: error: argument module_fname: can't open '{ADJACENCIES_FNAME}'

### ISSUE THREAD

**Issue by Zifeng1995** [aertslab/SCENICprotocol#14]
There is something wrong when I fellow the example. 
![image](https://user-images.githubusercontent.com/53402047/83985030-3c35ae80-a96a-11ea-89c5-7d1def4e4a42.png)
It said that No such file or directory: '{ADJACENCIES_FNAME}'.
But I checked the file, it had no problem.
![image](https://user-images.githubusercontent.com/53402047/83985165-acdccb00-a96a-11ea-9f9f-f7ab104daa1b.png)
Can anyone help me?

**Comment by cflerin** [comment]
Hmm, this should work, I'm not quite sure why it's causing a problem. Are you using a Windows OS by any chance?

But instead, you can just build the pyscenic command by pasting in the paths to your input files instead of letting the variable substitution do the work. So it would be something like this, using your own paths:
```
!pyscenic ctx \
    /path/to/adjacencies.tsv \
    /path/to/dbs_param \
...
```

**Comment by Zifeng1995** [comment]
> 嗯，这应该起作用，我不太确定为什么会引起问题。您是否正在使用Windows操作系统？
> 
> 但是，您可以通过粘贴输入文件的路径来构建pyscenic命令，而不是让变量替换来完成工作。因此，使用您自己的路径将是这样的：
> 
> ```
> !pyscenic ctx \
>     /path/to/adjacencies.tsv \
>     /path/to/dbs_param \
> ...
> ```

thanks, it works when using own paths.
then I get too many warnings when doing aucell
like this
`2020-06-08 22:54:28,929 - pyscenic.recovery - WARNING - Less than 80% of the genes in ARNT are present in the expression matrix.
`
As a result, it showed nothing in the fig.
![image](https://user-images.githubusercontent.com/53402047/84047136-873cd980-a9dd-11ea-9649-a1748f8b6e01.png)

**Comment by cflerin** [comment]
@loupl , thanks for the information on this. It could be something to do with your (Jupyter?) environment, since if you run it with the absolute paths, it seems to work. I can't reproduce this here, though.

@Zifeng1995 , For your second issue, are you using the same expression matrix that you used to generate the GRN output (adjacencies.tsv)? Did you successfully run the `ctx` step (i.e. how many regulons did you get in the output)?

**Comment by Zifeng1995** [comment]
> @loupl，感谢您提供有关此信息。这可能与您的（Jupyter？）环境有关，因为如果您使用绝对路径运行它，那么它似乎可以工作。不过，我无法在此处重现此内容。
> 
> @ Zifeng1995，对于第二个问题，您是否使用与生成GRN输出相同的表达式矩阵（adjacencies.tsv）？您是否成功运行了该`ctx`步骤（即您在输出中获得了多少个规则）？

For the first issue, maybe I found the error. It may caused by output file setting, when I set the right output file, it could work well.

For the second issue, I showed my code and results as follows
`!pyscenic grn {EXP_MTX_QC_FNAME} {HUMAN_TFS_FNAME} -o {ADJACENCIES_FNAME} --num_workers 6
`
`2020-06-09 17:59:03,186 - pyscenic.cli.pyscenic - INFO - Loading expression matrix.

2020-06-09 17:59:53,384 - pyscenic.cli.pyscenic - INFO - Inferring regulatory networks.
/cluster/home/zfli/anaconda2/envs/scanpy_env/lib/python3.6/site-packages/distributed/node.py:155: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 37612 instead
  http_address["port"], self.http_server.port
preparing dask client
parsing input
/cluster/home/zfli/anaconda2/envs/scanpy_env/lib/python3.6/site-packages/arboreto/algo.py:214: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  expression_matrix = expression_data.as_matrix()
creating dask graph
6 partitions
computing dask graph
not shutting down client, client was created externally
finished
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing

2020-06-10 00:19:09,618 - pyscenic.cli.pyscenic - INFO - Writing results to file.`

`!pyscenic ctx {ADJACENCIES_FNAME} {DBS_PARAM} \
            --annotations_fname {MOTIF_ANNOTATIONS_FNAME} \
            --expression_mtx_fname {EXP_MTX_QC_FNAME} \
            --output {MOTIFS_FNAME} \
            --mask_dropouts \
            --num_workers 6`
`/cluster/home/zfli/anaconda2/envs/scanpy_env/lib/python3.6/site-packages/dask/config.py:161: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}

2020-06-10 09:42:49,921 - pyscenic.cli.pyscenic - INFO - Creating modules.

2020-06-10 09:42:51,601 - pyscenic.cli.pyscenic - INFO - Loading expression matrix.

2020-06-10 09:43:49,077 - pyscenic.utils - INFO - Calculating Pearson correlations.

2020-06-10 09:43:49,077 - pyscenic.utils - WARNING - Note on correlation calculation: the default behaviour for calculating the correlations has changed after pySCENIC verion 0.9.16. Previously, the default was to calculate the correlation between a TF and target gene using only cells with non-zero expression values (mask_dropouts=True). The current default is now to use all cells to match the behavior of the R verision of SCENIC. The original settings can be retained by setting 'rho_mask_dropouts=True' in the modules_from_adjacencies function, or '--mask_dropouts' from the CLI.
	Dropout masking is currently set to [True].
/cluster/home/zfli/anaconda2/envs/scanpy_env/lib/python3.6/site-packages/pyscenic/utils.py:138: RuntimeWarning: invalid value encountered in greater
  regulations = (rhos > rho_threshold).astype(int) - (rhos < -rho_threshold).astype(int)
/cluster/home/zfli/anaconda2/envs/scanpy_env/lib/python3.6/site-packages/pyscenic/utils.py:138: RuntimeWarning: invalid value encountered in less
  regulations = (rhos > rho_threshold).astype(int) - (rhos < -rho_threshold).astype(int)

2020-06-10 09:44:11,245 - pyscenic.utils - INFO - Creating modules.

2020-06-10 09:45:23,475 - pyscenic.cli.pyscenic - INFO - Loading databases.

2020-06-10 09:45:23,475 - pyscenic.cli.pyscenic - INFO - Calculating regulons.
[###########                             ] | 27% Completed | 24min  8.9s
2020-06-10 10:09:34,132 - pyscenic.transform - WARNING - Less than 80% of the genes in ZNF10 could be mapped to hg38__refseq-r80__500bp_up_and_100bp_down_tss.mc9nr. Skipping this module.
[########################################] | 100% Completed |  1hr  2min 24.3s

2020-06-10 10:47:49,662 - pyscenic.cli.pyscenic - INFO - Writing results to file.`

by the way, I want to know the difference between {EXP_MTX_QC_FNAME} and {EXP_MTX_FNAME}, thanks a lot!!

**Comment by loupl** [comment]
@cflerin no problem at all and thanks for checking as well! I couldn't fully isolate the problem but my best guess right now is that it arises because of how I format the strings passed as filenames. I'm combining calls to `os.path.join()` with `"some_{variable}_path".format(variable=variable_part_of_filename)` to generate a `path/to/file`.  A quick check of the result with `os.path.isfile()` returns `True` but passing the `path/to/file` as suggested in the tutorial results in the above error. Separating the substitution from the `os.path.join()` seems to solve the problem. I don't fully understand what is going on but I suppose it has to do with how strings are handled by the different python functions and/or subsequently by jupyter in the case of variable substitution for calls to the command line.

**Comment by cflerin** [comment]
Hi @Zifeng1995 , Ok it does look like you're using the same expression matrix for both steps, which is good (though you haven't shown the AUCell commands). This should be `EXP_MTX_QC_FNAME`, which is after some basic filtering and preprocessing steps using Scanpy (`EXP_MTX_FNAME` is pre-filtering for this notebook). If you're substituting your own paths, you might want to check also that the matrices are not getting switched. What happens now when you run the AUCell step? I wouldn't expect to get those warnings and the plot you showed.

@loupl , I really don't know about this one. I checked it again in a new notebook and a few different python kernels and I'm still not getting the error, with or without `os.path.join`... Thanks for your input in any case!

**Comment by Zifeng1995** [comment]
> Hi @Zifeng1995 , Ok it does look like you're using the same expression matrix for both steps, which is good (though you haven't shown the AUCell commands). This should be `EXP_MTX_QC_FNAME`, which is after some basic filtering and preprocessing steps using Scanpy (`EXP_MTX_FNAME` is pre-filtering for this notebook). If you're substituting your own paths, you might want to check also that the matrices are not getting switched. What happens now when you run the AUCell step? I wouldn't expect to get those warnings and the plot you showed.
> 
> @loupl , I really don't know about this one. I checked it again in a new notebook and a few different python kernels and I'm still not getting the error, with or without `os.path.join`... Thanks for your input in any case!

Unluckily, I still get those warings.
```
def derive_regulons(motifs, db_names=('hg38__refseq-r80__500bp_up_and_100bp_down_tss.mc9nr',
                       'hg38__refseq-r80__10kb_up_and_down_tss.mc9nr')):
    motifs.columns = motifs.columns.droplevel(0)

    def contains(*elems):
        def f(context):
            return any(elem in context for elem in elems)
        return f

    # For the creation of regulons we only keep the 10-species databases and the activating modules. We also remove the
    # enriched motifs for the modules that were created using the method 'weight>50.0%' (because these modules are not part
    # of the default settings of modules_from_adjacencies anymore.
    motifs = motifs[
        np.fromiter(map(compose(op.not_, contains('weight>50.0%')), motifs.Context), dtype=np.bool) & \
        np.fromiter(map(contains(*db_names), motifs.Context), dtype=np.bool) & \
        np.fromiter(map(contains('activating'), motifs.Context), dtype=np.bool)]

    # We build regulons only using enriched motifs with a NES of 3.0 or higher; we take only directly annotated TFs or TF annotated
    # for an orthologous gene into account; and we only keep regulons with at least 10 genes.
    regulons = list(filter(lambda r: len(r) >= 10, df2regulons(motifs[(motifs['NES'] >= 3.0) 
                                                                      & ((motifs['Annotation'] == 'gene is directly annotated')
                                                                        | (motifs['Annotation'].str.startswith('gene is orthologous to')
                                                                           & motifs['Annotation'].str.endswith('which is directly annotated for motif')))
                                                                     ])))
    
    # Rename regulons, i.e. remove suffix.
    return list(map(lambda r: r.rename(r.transcription_factor), regulons))
```
```
regulons = derive_regulons(df_motifs)
REGULONS_DAT_FNAME = os.path.join(RESULTS_FOLDERNAME, '{}.regulons.dat'.format(DATASET_ID))
# Pickle these regulons.
with open(REGULONS_DAT_FNAME, 'wb') as f:
    pickle.dump(regulons, f)
AUCELL_MTX_FNAME = os.path.join(RESULTS_FOLDERNAME, '{}.auc.csv'.format(DATASET_ID))
EXP_MTX_FNAME = os.path.join(RESULTS_FOLDERNAME, '{}.tpm.csv'.format(DATASET_ID))
df_tpm = pd.read_csv("/cluster/home/zfli/RProject/MM_single/SCENIC/results/X.csv")
%%time
auc_mtx = aucell(df_tpm, regulons, num_workers=6)
auc_mtx.to_csv(AUCELL_MTX_FNAME)
```
The warnings is too long, as followed
```
2020-06-10 11:35:54,901 - pyscenic.recovery - WARNING - Less than 80% of the genes in E2F6 are present in the expression matrix.
2020-06-10 11:35:55,006 - pyscenic.recovery - WARNING - Less than 80% of the genes in NFATC3 are present in the expression matrix.
2020-06-10 11:35:54,902 - pyscenic.recovery - WARNING - Less than 80% of the genes in ARNT are present in the expression matrix.
2020-06-10 11:35:54,959 - pyscenic.recovery - WARNING - Less than 80% of the genes in HSF4 are present in the expression matrix.
2020-06-10 11:35:55,077 - pyscenic.recovery - WARNING - Less than 80% of the genes in SETDB1 are present in the expression matrix.
2020-06-10 11:35:55,111 - pyscenic.recovery - WARNING - Less than 80% of the genes in E2F7 are present in the expression matrix.
2020-06-10 11:35:55,111 - pyscenic.recovery - WARNING - Less than 80% of the genes in NFE2L2 are present in the expression matrix.
2020-06-10 11:35:55,116 - pyscenic.recovery - WARNING - Less than 80% of the genes in SIX5 are present in the expression matrix.

```

**Comment by cflerin** [comment]
Hi @Zifeng1995 ,

You must have used two different expression matrices between generating the regulons (`grn`+`ctx`) and calculating the cellular enrichments (`aucell`). I can't think of any other explanation for the warnings you're showing. I assume your AUC matrix is then just completely empty? The only other thing I could think of is maybe the expression matrix is transposed, or the gene names were dropped somehow.

**Comment by Zifeng1995** [comment]
> 嗨@ Zifeng1995，
> 
> 在生成调节子（`grn`+ `ctx`）和计算细胞富集（`aucell`）之间，必须使用两种不同的表达矩阵。对于您显示的警告，我想不出任何其他解释。我认为您的AUC矩阵就完全是空的了吗？我唯一想到的另一件事可能是表达矩阵被换位，或者基因名称以某种方式被删除。

I follewed the tutorial called SCENIC Protocol - Case study - Cancer data sets. 
```
EXP_MTX_TPM_FNAME = os.path.join(RESOURCES_FOLDERNAME, 'GSE115978_tpm.csv')
df_tpm = pd.read_csv(EXP_MTX_TPM_FNAME, index_col=0)
adata = sc.AnnData(X=df_tpm.T.sort_index())
adata.to_df().to_csv(EXP_MTX_QC_FNAME)
!pyscenic grn {EXP_MTX_QC_FNAME} {HUMAN_TFS_FNAME} -o {ADJACENCIES_FNAME} --num_workers 4
!pyscenic ctx {ADJACENCIES_FNAME} {DBS_PARAM} \
            --annotations_fname {MOTIF_ANNOTATIONS_FNAME} \
            --expression_mtx_fname {EXP_MTX_QC_FNAME} \
            --output {MOTIFS_FNAME} \
            --num_workers 26
auc_mtx = aucell(df_tpm.T, regulons, num_workers=26)
```
![image](https://user-images.githubusercontent.com/53402047/84995171-4469c700-b17e-11ea-96ee-14437b5c590c.png)

The expression matrix you used in this notebook contains the actual expression values (one column per gene, one row per cell). But in the tutorial named PBMC10k_SCENIC-protocol-CLI, you used loompy documentation as input, this matrix contains the actual expression values (one column per cell, one row per gene). So I want to know the clear  format of input.

**Comment by cflerin** [comment]
@Zifeng1995 , You can use either the raw expression counts, or more processed expression data (log-transformed, normalized, etc.) as input. See also https://github.com/aertslab/pySCENIC/issues/178.

**Comment by Zifeng1995** [comment]
> @ Zifeng1995，您可以使用原始表达式计数，也可以使用更多处理的表达式数据（对数转换，规范化等）作为输入。另请参阅[aertslab / pySCENIC＃178](https://github.com/aertslab/pySCENIC/issues/178)。

I may not have made it clear. I want to know the format of input is like cells x genes or genes x cells? 
cells x genes:
  gene gene gene
cell
cell 
cell
or genes x cells
    cell cell cell
gene
gene
gene
Thank you for your patience.

**Comment by cflerin** [comment]
Ah ok I see what you mean. For a tsv/csv matrix input, you can have:

* rows=cells x columns=genes (using the default pyscenic settings)
* rows=genes x columns=cells (using the `--transpose` setting)

If you use the wrong combination of `--transpose` and expression matrix, you should get an error from pyscenic.

**Comment by Zifeng1995** [comment]
> 好的，我明白你的意思了。对于ts​​v / csv矩阵输入，您可以具有：
> 
> * rows = cells x column = genes（使用默认的pyscenic设置）
> * rows = genes x column = cells（使用`--transpose`设置）
> 
> 如果您使用`--transpose`和矩阵的错误组合，则应该从pyscenic中得到一个错误。

However, in your tutorial named PBMC10k_SCENIC-protocol-CLI, you used the loom file as input. The format of loom file is "rows = genes x column = cells".
And the code of grn is as follows:
`!pyscenic grn {f_loom_path_scenic} {f_tfs} -o adj.csv --num_workers 4`
which seems to use the default pyscenic settings.
So I am so confused that is there anything wrong with the tutorial?

**Comment by cflerin** [comment]
Yes, the loom format is rows=genes x columns=cells, but this is all handled automatically when loading from loom, it's not related at all to the plain text expression format (`--transpose` doesn't apply when loading from loom, it's always in the correct format).

Your screenshow shows cells in rows, genes in columns, so the default setting should be appropriate (without transpose). If you prefer to create a loom from the anndata object, it's straightforward:
```
import loompy as lp
import numpy as np

row_attrs = { 
    "Gene": np.array(adata.var.index) ,
}
col_attrs = { 
    "CellID":  np.array(adata.obs.index) ,
    "nGene": np.array( np.sum(adata.X.transpose()>0 , axis=0)).flatten() ,
    "nUMI": np.array( np.sum(adata.X.transpose() , axis=0)).flatten() ,
}
lp.create( f_loom_path_unfilt, adata.X.transpose(), row_attrs, col_attrs )
```
You can then use this file for all subsequent steps.

**Comment by Zifeng1995** [comment]
> 是的，织机的格式是rows = genes x column = cells，但是从织机加载时，这都是自动处理的，它与纯文本表达格式`--transpose`完全无关（从织机加载时不适用，它始终在正确的格式）。
> 
> 屏幕显示以行显示细胞，以列显示基因，因此默认设置应适当（无转置）。如果您希望从andata对象创建一个织机，那就很简单了：
> 
> ```
> import loompy as lp
> import numpy as np
> 
> row_attrs = { 
>     "Gene": np.array(adata.var.index) ,
> }
> col_attrs = { 
>     "CellID":  np.array(adata.obs.index) ,
>     "nGene": np.array( np.sum(adata.X.transpose()>0 , axis=0)).flatten() ,
>     "nUMI": np.array( np.sum(adata.X.transpose() , axis=0)).flatten() ,
> }
> lp.create( f_loom_path_unfilt, adata.X.transpose(), row_attrs, col_attrs )
> ```
> 
> 然后，您可以将该文件用于所有后续步骤。

Thank you very much for solving the problem that bothers me for a long time!!!

**Comment by cflerin** [comment]
ok, glad to hear that helped!

**Comment by yanwuanxin** [comment]
when I use founction of aucell to score, the warning message as follows `Less than 80% of the genes in Tumor are present in the expression matrix.` 
The code I use: `aucell(exp_mtx=df,signatures=gs,auc_threshold=0.05,seed=2,normalize=True)`
Does anyone meet the same problem and have a solution？

**Comment by yanwuanxin** [comment]
I've found the reason：
`AUCell scoring expects the overlap of genes in signature and dataset to be larger than 80%, else it doesn't return scores`
