### ISSUE TITLE
KeyError: 'Celltype_Garnett' 

### ISSUE THREAD

**Issue by ChenchenWangiSummer** [aertslab/SCENICprotocol#16]
Hi,
   I follow the pySCENIC protocol: PBMC10k downstream analyses.I get the following error when trying to extract relevant data from the integrated loom file: 

cellAnnot = pd.concat(
    [
        pd.DataFrame( lf.ca.Celltype_Garnett, index=lf.ca.CellID ),
        pd.DataFrame( lf.ca.ClusterID, index=lf.ca.CellID ),
        pd.DataFrame( lf.ca.Louvain_clusters_Scanpy, index=lf.ca.CellID ),
        pd.DataFrame( lf.ca.Percent_mito, index=lf.ca.CellID ),
        pd.DataFrame( lf.ca.nGene, index=lf.ca.CellID ),
        pd.DataFrame( lf.ca.nUMI, index=lf.ca.CellID ),
    ],
    axis=1
)

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/loompy/attribute_manager.py", line 115, in __getattr__
    vals = self.__dict__["storage"][name]
KeyError: 'Celltype_Garnett'

Any suggestions?
Thanks!

**Comment by cflerin** [comment]
Hi @ChenchenWangiSummer ,

It looks like your loom file is missing that column attribute. You can verify by looking at the output of `lf.ca.keys()`:
```
>>> lf.ca.keys()
['CellID',
 'Celltype_Garnett',
 'ClusterID',
 'Clusterings',
 'Embedding',
 'Embeddings_X',
 'Embeddings_Y',
 'Louvain_clusters_Scanpy',
 'Percent_mito',
 'RegulonsAUC',
 'nGene',
 'nUMI']
```

If you created the loom file as part of the tutorial, you probably didn't include the Garnett cell type calls (you can find the file [here](https://github.com/aertslab/SCENICprotocol/blob/master/notebooks/pbmc10k_garnett_results.txt)).

You can also download an "official" version of this loom from the SCope session [here](http://scope.aertslab.org/#/Protocol_Cases/Protocol_Cases%2FPBMC10k.loom/gene). This file will have the `Celltype_Garnett` annotation.

Or you can skip the loading of that attribute by just commenting this line out:
```pd.DataFrame( lf.ca.Celltype_Garnett, index=lf.ca.CellID ),```
and use the Louvain cluster labels in place of cell type for the rest of the tutorial.

**Comment by ChenchenWangiSummer** [comment]
Hi, cflerin 
  I follow the pySCENIC protocol: PBMC10k, and  try to include the Garnett cell type calls. Could I use the metaJson like this: 

```
metaJson["annotations"] = [
    {
        "name": "Celltype_Garnett",
        "values": list(set(adata.obs['Celltype_Garnett'].astype(np.str)))
    },
```
but when I try, i got the error:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2897, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Celltype_Garnett']

yes, I can use the Louvain cluster labels in place of cell type for the rest of the tutorial.
but I want to know how can i get the Garnett cell type attribute in my own loom file after AUCell analysis.
Thanks a lot!
CC

> Hi @ChenchenWangiSummer ,
> 
> It looks like your loom file is missing that column attribute. You can verify by looking at the output of `lf.ca.keys()`:
> 
> ```
> >>> lf.ca.keys()
> ['CellID',
>  'Celltype_Garnett',
>  'ClusterID',
>  'Clusterings',
>  'Embedding',
>  'Embeddings_X',
>  'Embeddings_Y',
>  'Louvain_clusters_Scanpy',
>  'Percent_mito',
>  'RegulonsAUC',
>  'nGene',
>  'nUMI']
> ```
> 
> If you created the loom file as part of the tutorial, you probably didn't include the Garnett cell type calls (you can find the file [here](https://github.com/aertslab/SCENICprotocol/blob/master/notebooks/pbmc10k_garnett_results.txt)).
> 
> You can also download an "official" version of this loom from the SCope session [here](http://scope.aertslab.org/#/Protocol_Cases/Protocol_Cases%2FPBMC10k.loom/gene). This file will have the `Celltype_Garnett` annotation.
> 
> Or you can skip the loading of that attribute by just commenting this line out:
> `pd.DataFrame( lf.ca.Celltype_Garnett, index=lf.ca.CellID ),`
> and use the Louvain cluster labels in place of cell type for the rest of the tutorial.

**Comment by cflerin** [comment]
Here's what I would do to add the cell type annotations to an existing loom file, which it sounds like you have already:

Using the file from:
```
wget https://raw.githubusercontent.com/aertslab/SCENICprotocol/master/notebooks/pbmc10k_garnett_results.txt
```

In python:
```
import pandas as pd
import loompy as lp
import numpy as np
import json
import base64
import zlib

lf = lp.connect('PBMC10k.loom', mode='r+', validate=False)

# read in the annotations and match to the loom CellID:
annot = pd.read_csv('pbmc10k_garnett_results.txt', sep='\t', header=0, index_col=0)
annot2 = annot.reindex(lf.ca.CellID)
all(annot2.index == lf.ca.CellID)

# get the metadata out of the file:
meta = json.loads(zlib.decompress(base64.b64decode( lf.attrs.MetaData )))

# add the cell type annotations to the metadata:
meta['annotations'].extend(
    [{
        "name": "Celltype_Garnett",
        "values": list(set( annot2['cell_type'].astype(np.str) ))
    }]
)

# copy the altered metadata back into the loom (compression and encoding is required if the loom file was created with loompy 2):
lf.attrs['MetaData'] = base64.b64encode(zlib.compress(json.dumps(meta).encode('ascii'))).decode('ascii')

# finally, add the cell type values to the column attributes:
lf.ca.Celltype_Garnett = np.array( annot2['cell_type'].values )

lf.close()
```

**Comment by daisyyr** [comment]
> Here's what I would do to add the cell type annotations to an existing loom file, which it sounds like you have already:
> 
> Using the file from:
> 
> ```
> wget https://raw.githubusercontent.com/aertslab/SCENICprotocol/master/notebooks/pbmc10k_garnett_results.txt
> ```
> 
> In python:
> 
> ```
> import pandas as pd
> import loompy as lp
> import numpy as np
> import json
> import base64
> import zlib
> 
> lf = lp.connect('PBMC10k.loom', mode='r+', validate=False)
> 
> # read in the annotations and match to the loom CellID:
> annot = pd.read_csv('pbmc10k_garnett_results.txt', sep='\t', header=0, index_col=0)
> annot2 = annot.reindex(lf.ca.CellID)
> all(annot2.index == lf.ca.CellID)
> 
> # get the metadata out of the file:
> meta = json.loads(zlib.decompress(base64.b64decode( lf.attrs.MetaData )))
> 
> # add the cell type annotations to the metadata:
> meta['annotations'].extend(
>     [{
>         "name": "Celltype_Garnett",
>         "values": list(set( annot2['cell_type'].astype(np.str) ))
>     }]
> )
> 
> # copy the altered metadata back into the loom (compression and encoding is required if the loom file was created with loompy 2):
> lf.attrs['MetaData'] = base64.b64encode(zlib.compress(json.dumps(meta).encode('ascii'))).decode('ascii')
> 
> # finally, add the cell type values to the column attributes:
> lf.ca.Celltype_Garnett = np.array( annot2['cell_type'].values )
> 
> lf.close()
> ```

Hi, cflerin
I tried to add celltype_Garnett into meta data of the loom file. However, I ran into errors when conducting this line

` lf.attrs.MetaData = base64.b64encode(zlib.compress(json.dumps(meta).encode('ascii'))).decode('ascii')`


```
KeyError                                  Traceback (most recent call last)
<ipython-input-47-906136c26afb> in <module>
     13 # copy the altered metadata back into the loom (compression and encoding is required if the loom file was created with loompy 2):
     14 #lf.attrs['MetaData'] = zlib.compress(json.dumps(meta).encode('ascii'))
---> 15 lf.attrs.MetaData = base64.b64encode(zlib.compress(json.dumps(meta).encode('ascii'))).decode('ascii')
     16 #lf.attrs['MetaData'] = meta
     17 

~/cpdb-venv/lib64/python3.6/site-packages/loompy/global_attribute_manager.py in __setattr__(self, name, val)
     84                                         normalized = loompy.normalize_attr_values(val, True)
     85                                         if name in self.f["attrs"]:
---> 86                                                 del self.f["attrs"][name]
     87                                         if not np.isscalar(normalized) and normalized.dtype == np.object_:
     88                                                 self.ds._file.create_dataset("attrs/" + name, data=normalized, dtype=h5py.special_dtype(vlen=str))

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

~/cpdb-venv/lib64/python3.6/site-packages/h5py/_hl/group.py in __delitem__(self, name)
    397     def __delitem__(self, name):
    398         """ Delete (unlink) an item from this group. """
--> 399         self.id.unlink(self._e(name))
    400 
    401     @with_phil

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5g.pyx in h5py.h5g.GroupID.unlink()

KeyError: "Couldn't delete link (no write intent on file)"
```

What might be the problem?

**Comment by cflerin** [comment]
Hi @daisyyr ,

Did you open the loom connection in read-write mode? (`mode='r+'`).

**Comment by daisyyr** [comment]
> Hi @daisyyr ,
> 
> Did you open the loom connection in read-write mode? (`mode='r+'`).

Thanks for your quick reply and it really helps. It turned out I didn't change the mode of loom connection. I just made the simplest mistake.
Thank you so so so much!

**Comment by ektapathak08** [comment]
Hello,
 I am working on a single cell RNA-seq dataset that has two samples for each Case and control.  I imported the count matrices in Seurat and merged them to a single Seurat object. Next, I performed some initial filtering and doublet removal. then I performed SCTransform and saved the transpose of normalized count matrix to csv format. I imported csv file to the scenic workflow for "Reading in expression data: from a text file".

 I have generated the output loom file from aucell.
 But now I am stuck at the SCope compatible loom file generation. I am getting KeyError: 'MetaData'

How to add Metadata to the loom file at this step.

Please suggest how to proceed further.

python add_visualization.py  --loom_input aucell_SCENIC_1.loom --loom_output scenic_visualize.loom  --num_workers 8
Traceback (most recent call last):
  File "/home/ekta/Documents/1_ekta_research_work/covid_Pancreas/Qc_doublet_removal/res_4_5/analysis/anticipated_revision/TF/export_to_loom.py", line 135, in read_loom
    global_attrs["MetaData"] = SCopeLoom.decompress_decode(value=global_attrs["MetaData"])
KeyError: 'MetaData'


Thanks
Ekta
