### ISSUE TITLE
Tornado.util.TimeoutError timed out after 20 s

### ISSUE THREAD

**Issue by sidrahmaryam** [aertslab/SCENICprotocol#17]
Hey everyone! I am trying to run scenic protocol, for network regulatory inference.

The code command is

` pyscenic grn --num_workers 20 --output adj.tsv --method grnboost2 filtered.loom hs_hgnc_tfs.txt
`

And I am getting the following error

home/sidrah19220/anaconda3/envs/scenic_protocol/lib/python3.6/site-packages/dask/config.py:161: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details. data = yaml.load(f.read()) or {} 2020-07-21 22:55:37,466 - pyscenic.cli.pyscenic - INFO - Loading expression matrix. 2020-07-21 22:55:37,616 - pyscenic.cli.pyscenic - INFO - Inferring regulatory networks. /home/sidrah19220/anaconda3/envs/scenic_protocol/lib/python3.6/site-packages/dask/config.py:161: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details. data = yaml.load(f.read()) or {} tornado.application - ERROR - Multiple exceptions in yield list Traceback (most recent call last): File "/home/sidrah19220/anaconda3/envs/scenic_protocol/lib/python3.6/site-packages/tornado/gen.py", line 501, in callback result_list.append(f.result()) File "/home/sidrah19220/anaconda3/envs/scenic_protocol/lib/python3.6/site-packages/tornado/gen.py", line 748, in run yielded = self.gen.send(value) File "/home/sidrah19220/anaconda3/envs/scenic_protocol/lib/python3.6/site-packages/distributed/deploy/local.py", line 316, in _start_worker raise gen.TimeoutError("Worker failed to start") tornado.util.TimeoutError: Worker failed to start tornado.application - ERROR - Multiple exceptions in yield list File "/home/sidrah19220/anaconda3/envs/scenic_protocol/lib/python3.6/site-packages/tornado/gen.py", line 501, in callback result_list.append(f.result()) File "/home/sidrah19220/anaconda3/envs/scenic_protocol/lib/python3.6/site-packages/tornado/gen.py", line 748, in run yielded = self.gen.send(value) File "/home/sidrah19220/anaconda3/envs/scenic_protocol/lib/python3.6/site-packages/distributed/deploy/local.py", line 316, in _start_worker raise gen.TimeoutError("Worker failed to start") tornado.util.TimeoutError: Worker failed to start Exception ignored in: <bound method="" localcluster.del="" of="" localcluster('tcp:="" 127.0.0.1:38723',="" workers="0," ncores="0)>" traceback="" (most="" recent="" call="" last):="" file="" "="" home="" sidrah19220="" anaconda3="" envs="" scenic_protocol="" lib="" python3.6="" site-packages="" distributed="" deploy="" local.py",="" line="" 444,="" in="" del="" file="" "="" home="" sidrah19220="" anaconda3="" envs="" scenic_protocol="" lib="" python3.6="" site-packages="" distributed="" deploy="" local.py",="" line="" 385,="" in="" close="" file="" "="" home="" sidrah19220="" anaconda3="" envs="" scenic_protocol="" lib="" python3.6="" site-packages="" distributed="" deploy="" local.py",="" line="" 249,="" in="" sync="" file="" "="" home="" sidrah19220="" anaconda3="" envs="" scenic_protocol="" lib="" python3.6="" site-packages="" distributed="" utils.py",="" line="" 326,="" in="" sync="" <strong="">tornado.util.TimeoutError: timed out after 20 s

Please suggest a solution

**Comment by sidrahmaryam** [comment]
Thanks a lot. It solved the issue. 

But the generated loom file, it does not show any results in the SCope.
Can you please tell what could have gone wrong? I followed all the steps.

**Comment by cflerin** [comment]
Hi @sidrahmaryam ,

I'm not totally clear on which tutorial you're following. The Nextflow workflow in this repository will generate a loom file with multiple embeddings included for display in SCope. But if you're running pySCENIC CLI, the `aucell` step produces a loom file without any embeddings. If this is the case, you could add them yourself following one of the tutorials ([for example](http://htmlpreview.github.io/?https://github.com/aertslab/SCENICprotocol/blob/master/notebooks/PBMC10k_SCENIC-protocol-CLI.html)). I will push an independent script to accomplish this directly from the `aucell` output soon.

I'll close this since we solved your original error, but feel free to ask if you're still having problems.

**Comment by cflerin** [comment]
Also, see [this faq entry](https://pyscenic.readthedocs.io/en/latest/faq.html#how-can-i-create-a-scope-compatible-loom-file) for an example of how to take the AUC loom and add a t-SNE and UMAP to it for use in SCope.
