### ISSUE TITLE
Problems with saving AUCell and regulon data into loom file using export2loom

### ISSUE THREAD

**Issue by sykim14** [aertslab/SCENICprotocol#18]
Hi, I am trying to save AUCell and regulon data as loom file for further analysis in R.

I tried two codes,
`export2loom(ex_mtx = ex_matrix, auc_mtx = auc_mtx, regulons = [r.rename(r.name.replace('(',' (')) for r in regulons], out_fname = "/path/file_name.loom")`

and 

`export2loom(ex_mtx = ex_matrix, auc_mtx = auc_mtx, regulons = [r.rename(r.name.replace('(+)',' ('+str(len(r))+'g)')) for r in regulons], out_fname = "/path/file_name.loom")`

However, it is taking more than 1 day to run. 
Does this normally take that long or there is something wrong with my code?
I could save auc_mtx into csv files.

Thank you

**Comment by cflerin** [comment]
This issue is probably related to https://github.com/aertslab/pySCENIC/issues/188 and the binarization step hanging for some reason.

**Comment by cflerin** [comment]
Closing this -- we can keep discussing in https://github.com/aertslab/pySCENIC/issues/188
