### ISSUE TITLE
Generating final loom file

### ISSUE THREAD

**Issue by sidrahmaryam** [aertslab/SCENICprotocol#19]
Hello,
while making the final loom file, I am getting this error:

**Column attribute 'Embeddings_X' is not the same length (478) as number of columns in main matrix (239)**

please help in this regard

**Comment by cflerin** [comment]
Can you give me some clues as to the command you're running? Can you paste the full output into a code block?

**Comment by Nikom13** [comment]
> Can you give me some clues as to the command you're running? Can you paste the full output into a code block?

How was the issue resolved? 

Thanks in advance!
