### ISSUE TITLE
Problem with further exploring module files in iRegulon

### ISSUE THREAD

**Issue by Zifeng1995** [aertslab/SCENICprotocol#20]
Hi here,
I followed the jupyter notebook named PBMC10k_downstream-analysis to explore module files in iRegulon.
When I picked out modules for my target genes, there's something wrong.
```
adjacencies = pd.read_csv("/cluster/home/zfli/RProject/MM_single/SCENIC/results/MM.adjacencies.tsv", index_col=False, sep='\t')
exprMat=pd.read_csv(EXP_MTX_QC_FNAME,index_col=0)
from pyscenic.utils import modules_from_adjacencies
modules = list(modules_from_adjacencies(adjacencies, exprMat))
tf = 'MYBL2'
tf_mods = [ x for x in modules if x.transcription_factor==tf ]
```
```
for i,mod in enumerate( tf_mods ):
    print( f'{tf} module {str(i)}: {len(mod.genes)} genes' )`
```
MYBL2 module 0: 4301 genes
MYBL2 module 1: 3240 genes
MYBL2 module 2: 51 genes
MYBL2 module 3: 47 genes
MYBL2 module 4: 644 genes
MYBL2 module 5: 3351 genes

```
print( f'{tf} regulon: {len(regulons[tf+"(+)"])} genes' )
```
TypeError                                 Traceback (most recent call last)
<ipython-input-50-fd43db78f5aa> in <module>
----> 1 print( f'{tf} regulon: {len(regulons[tf+"(+)"])} genes' )

TypeError: list indices must be integers or slices, not str

Then I checked the regulon list.
```
regulons[1]
```
Regulon(name='ALX1(+)', gene2weight=<frozendict {'NFATC3': 0.4666430402753485, 'LGALS3': 2.9417811594561583, 'PJA1': 0.7149351863285957, 'CA1': 2.9417811594561583, 'FLNA': 1.3756471078801764, 'TUBA1A': 0.37228583969436796, 'PRMT2': 1.0, 'RUNX1T1': 1.6734605118620007, 'LRRC23': 1.1354697828746674, 'ADI1': 0.9461970789505432, 'CD36': 1.0787344073180478, 'DTNB': 1.6851222353044415, 'BOLA2B': 1.9447241642326292, 'PACSIN2': 1.3756471078801764, 'ENTPD1': 1.0, 'ADGRE1': 1.6851222353044415, 'CPPED1': 4.292454650246219}>, gene2occurrence=<frozendict {}>, transcription_factor='ALX1', context=frozenset({'activating', 'taipale_cyt_meth__PROP1_TAATTRCGTTA_FL_meth.png'}), score=3.026860825133384, nes=0.0, orthologous_identity=0.0, similarity_qvalue=0.0, annotation='')

How can I adjust my codes? Thanks a lot!!!

**Comment by cflerin** [comment]
Hi @Zifeng1995 ,

Earlier in the tutorial, I've created the `regulons` object from the loom file like:
```
regulons = {}
for i,r in pd.DataFrame(lf.ra.Regulons,index=lf.ra.Gene).iteritems():
    regulons[i] =  list(r[r==1].index.values)
```
but I think you've loaded the regulons via:
```
from pyscenic.cli.utils import load_signatures
regulons = load_signatures('reg.csv')
```

To get the same output with the regulons in the format you have them, you could use the following code. The error you got was just to count the regulon target genes, and you'll have to update the code to write the regulons file as well:
```
regulon_of_interest = [ x for x in regulons if x.name==tf+"(+)" ][0]

# count target genes in the regulon of interest:
print( f'{tf} regulon: { len(regulon_of_interest.genes) } genes' )

# write regulons file:
with open( tf+'_regulon.txt', 'w') as f:
    for item in regulon_of_interest.genes:
        f.write("%s\n" % item)
```
Then you should be able to move on to the iRegulon step with these files.

**Comment by Zifeng1995** [comment]
> Hi @Zifeng1995 ,
> 
> Earlier in the tutorial, I've created the `regulons` object from the loom file like:
> 
> ```
> regulons = {}
> for i,r in pd.DataFrame(lf.ra.Regulons,index=lf.ra.Gene).iteritems():
>     regulons[i] =  list(r[r==1].index.values)
> ```
> 
> but I think you've loaded the regulons via:
> 
> ```
> from pyscenic.cli.utils import load_signatures
> regulons = load_signatures('reg.csv')
> ```
> 
> To get the same output with the regulons in the format you have them, you could use the following code. The error you got was just to count the regulon target genes, and you'll have to update the code to write the regulons file as well:
> 
> ```
> regulon_of_interest = [ x for x in regulons if x.name==tf+"(+)" ][0]
> 
> # count target genes in the regulon of interest:
> print( f'{tf} regulon: { len(regulon_of_interest.genes) } genes' )
> 
> # write regulons file:
> with open( tf+'_regulon.txt', 'w') as f:
>     for item in regulon_of_interest.genes:
>         f.write("%s\n" % item)
> ```
> 
> Then you should be able to move on to the iRegulon step with these files.

thanks for your help! Do you mind if I ask you one more thing? Is the module and regulon output files just the gene names? how   can these be used in iRegulon? I read the tutorial of iRegulon but still have no idea.
