### ISSUE TITLE
What is required to run SCENIC in a custom species?

### ISSUE THREAD

**Issue by alexthiery** [aertslab/SCENICprotocol#23]
Hi - I am interested in running SCENIC on zebrafish and chick datasets, but am unclear as to which files I need to generate to run this in a custom species. Any help would be much appreciated - thanks

**Comment by cflerin** [comment]
Hi @alexthiery ,

You can already run the GRN inference step in any species (provided you have a good list of transcription factors available), and generate unrefined modules from the GRN output. But for module refinement and regulon generation you would need a set of cisTarget databases for your species. Currently we only have databases available for human, mouse, and fly ([here](https://resources.aertslab.org/cistarget/)). But creating a new set of databases for other species is possible, and we are currently working on cleaning up our scripts and releasing them for use. This should be available soon and I will try to remember to update here when it's all ready.

**Comment by alexthiery** [comment]
Perfect. Thanks @cflerin. I think we will wait for the scripts to be released to make our own database. Thanks for creating a great tool!

**Comment by cflerin** [comment]
Hi @alexthiery ,

We now have an initial set of scripts and methods to generate your own database, if this is something you want to try. The instructions are in the early stages, but you can find them here: https://github.com/aertslab/create_cisTarget_databases . So I'll close this issue, and if there are issues with the database creation, you could raise a more specific issue in that repository.
