### ISSUE TITLE
Singularity: can't open file 'pyscenic'

### ISSUE THREAD

**Issue by f6v** [aertslab/SCENICprotocol#25]
I've installed `singularity` on fresh `ubuntu` instance and trying to run `scenic` according to the documentation:
```
singularity pull --name aertslab-pyscenic-0.9.18.sif shub://aertslab/pySCENIC:0.9.18
```
However, I get the error when running:
```
singularity run aertslab-pyscenic-0.9.18.sif pyscenic -h
```

> python3: can't open file 'pyscenic': [Errno 2] No such file or directory

I have also set up a kernel for Jypyter from singularity container, however Jupyter can't connect to it.

Are the instructions up to date? Am I missing something?

**Comment by f6v** [comment]
Pulling image from Singularity hub is obsolete, isn't it? I managed to build a singularity container from docker hub with version 0.10.3 and that seems to work for now.

**Comment by cflerin** [comment]
Hi @f6v ,

Yes, we largely stopped using Singularity hub after pyscenic 0.9.18 (I believe), and building from Docker Hub is the preferred method now. At the same time, your original command should have worked, as long as the image was built successfully. But it sounds like you got it working with the later version...
