### ISSUE TITLE
Abount mm_tfs.txt

### ISSUE THREAD

**Issue by hahia** [aertslab/SCENICprotocol#26]
Hello, I have a naive question.
Where can I download the mm_tfs.txt?
Thank you any comments

**Comment by cflerin** [comment]
No problem, you can find a copy in this repository:

https://raw.githubusercontent.com/aertslab/SCENICprotocol/master/example/allTFs_mm.txt

**Comment by pekjoonwu** [comment]
> No problem, you can find a copy in this repository:
> 
> https://raw.githubusercontent.com/aertslab/SCENICprotocol/master/example/allTFs_mm.txt

Hey I am wondering why you did not use this file which was included in the tutorial? https://github.com/aertslab/pySCENIC/blob/master/resources/mm_mgi_tfs.txt

Also, if I run with this text file, I would run into an error:
adjacencies = grnboost2(ex_matrix_sub, tf_names = tf_names, verbose = True)
preparing dask client
parsing input
creating dask graph
shutting down client and local cluster
finished
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "arboreto/algo.py", line 41, in grnboost2
    early_stop_window_length=early_stop_window_length, limit=limit, seed=seed, verbose=verbose)
  File "/arboreto/algo.py", line 128, in diy
    seed=seed)
  File "py_env/lib/python3.7/site-packages/arboreto/core.py", line 450, in create_graph
    all_meta_df = from_delayed(delayed_meta_dfs, meta=_META_SCHEMA)
  File "py_env/lib/python3.7/site-packages/dask/dataframe/io/io.py", line 591, in from_delayed
    parent_meta = delayed(make_meta)(dfs[0]).compute()
IndexError: list index out of range

Any idea why this happened? Many thanks in advance!!!
