### ISSUE TITLE
In running: PBMC10k_SCENIC-protocol-CLI.ipynb, please let know where this file: "exprMat" came from? thanks!

### ISSUE THREAD

**Issue by fzhang988** [aertslab/SCENICprotocol#30]
![image](https://user-images.githubusercontent.com/11845230/97456491-e5119400-1973-11eb-97dc-0adba5830f0a.png)

**Comment by cflerin** [comment]
Hi @fzhang988 ,

Sorry, that is indeed a typo, and `exprMat` should be the same expression matrix that you've been using throughout the rest of the tutorial (`adata.X`). There were some other sections where I was taking the expression matrix out of the loom file and this is where this object came from.
