### ISSUE TITLE
putting *.tsv file as input to run pySCENIC 

### ISSUE THREAD

**Issue by Shiywa** [aertslab/SCENICprotocol#32]
Hi, the `SCENICprotocol` in docker is maintained, while `scenic-nf` wasn't maintained.
my question is whether the *.tsv could be input for `SCENICprotocol` by parameter `--expr` like `scenic-nf`.

regards

**Comment by cflerin** [comment]
Hi @Shiywa ,

Sorry, but you can't use tsv input for this Nextflow pipeline, it will only work with loom. 

I would suggest however, that you could use [VSN-Pipelines](https://github.com/vib-singlecell-nf/vsn-pipelines) which is in a way the successor to this pipeline. It will take a wide variety of input files, tsv included. There are a number of workflows in VSN, but if you want something comparable to what's found in SCENICprotocol, you would use `single_sample_scenic`. See [here](https://vsn-pipelines-examples.readthedocs.io/en/latest/PBMC10k.html) for an example tutorial.
