### ISSUE TITLE
Can the number of cells exceed 65536?

### ISSUE THREAD

**Issue by XiaoyuLi-smu** [aertslab/SCENICprotocol#35]
It seems that when runSCENIC_4_aucell_binarize call the hclust function in stats and the number of cells exceed 65536, it can't work.
scenicOptions <- runSCENIC_4_aucell_binarize(scenicOptions)
output:
Binary regulon activity: 26 TF regulons x 79211 cells.
(43 regulons including 'extended' versions)
26 regulons are active in more than 1% (792.11) cells.
Error in hclust(d, method = hclustfun) : 
  size cannot be NA nor exceed 65536

version
scenic 1.2.2
stats 4.0.3

**Comment by XiaoyuLi-smu** [comment]
oh, it should be the problem of NMF package.
The traceback indicates the error occurs when the following code is run.
NMF::aheatmap(binaryMat, scale = "none", revC = TRUE, 
            main = selRegs, annCol = cellInfo[colnames(binaryMat), 
              , drop = FALSE], annColor = colVars, Rowv = rowv, 
            Colv = colv, color = c("white", "black"), 
            filename = fileName)

**Comment by cflerin** [comment]
Hi @XiaoyuLi-smu ,

This seems to be an R SCENIC issue, can you post there if you are still having the problem?

https://github.com/aertslab/SCENIC

**Comment by wujp1993** [comment]
hi, how do you  solve the problem
