### ISSUE TITLE
No module named 'sklearn.manifold.t_sne'

### ISSUE THREAD

**Issue by f6v** [aertslab/SCENICprotocol#41]
I'm running the following import:
```
from pyscenic.export import export2loom, add_scenic_metadata
```

And get the error:
```
>>> from pyscenic.export import export2loom, add_scenic_metadata

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/f6v/miniconda3/envs/scenic_protocol/lib/python3.6/site-packages/pyscenic/export.py", line 7, in <module>
    from sklearn.manifold.t_sne import TSNE
ModuleNotFoundError: No module named 'sklearn.manifold.t_sne'
```

Seems like `TSNE` is just under `sklearn.manifold`. See [docs](https://scikit-learn.org/stable/modules/generated/sklearn.manifold.TSNE.html).

sklearn version: '0.24.1'

**Comment by cflerin** [comment]
Hi @f6v ,

sklearn moved the tsne module at some point. If you downgrade to scikit-learn==0.21.3 this import should work again. (I should have locked the package requirements for this).

**Comment by JohnWang1997** [comment]
You can just modify the code file 'export.py', and change 'from sklearn.manifold.t_sne import TSNE' to 'from sklearn.manifold._t_sne import TSNE'.
