### ISSUE TITLE
OSError: Unable to open file (file signature not found)

### ISSUE THREAD

**Issue by HerpelinckT** [aertslab/SCENICprotocol#42]
Hi,

I am following the procedure outlined in the Nature Protocols paper. At step 7, cellular enrichment, I run into an error. The command I'm using is: `pyscenic aucell 
PBMC10k_filtered.loom 
reg.csv 
--output PBMC10k_SCENIC.loom 
--num_workers 20`

This results in the following output in the CLI:

> 2021-04-09 17:54:44,095 - pyscenic.cli.pyscenic - INFO - Loading expression matrix.
> Traceback (most recent call last):
>   File "/home/luna.kuleuven.be/u0124158/miniconda3/envs/pyscenic/bin/pyscenic", line 8, in <module>
>     sys.exit(main())
>   File "/home/luna.kuleuven.be/u0124158/miniconda3/envs/pyscenic/lib/python3.6/site-packages/pyscenic/cli/pyscenic.py", line 485, in main
>     args.func(args)
>   File "/home/luna.kuleuven.be/u0124158/miniconda3/envs/pyscenic/lib/python3.6/site-packages/pyscenic/cli/pyscenic.py", line 216, in aucell_command
>     args.gene_attribute)
>   File "/home/luna.kuleuven.be/u0124158/miniconda3/envs/pyscenic/lib/python3.6/site-packages/pyscenic/cli/utils.py", line 116, in load_exp_matrix
>     return load_exp_matrix_as_loom(fname, return_sparse, attribute_name_cell_id, attribute_name_gene)
>   File "/home/luna.kuleuven.be/u0124158/miniconda3/envs/pyscenic/lib/python3.6/site-packages/pyscenic/cli/utils.py", line 69, in load_exp_matrix_as_loom
>     with lp.connect(fname,mode='r',validate=False) as ds:
>   File "/home/luna.kuleuven.be/u0124158/.local/lib/python3.6/site-packages/loompy/loompy.py", line 1389, in connect
>     return LoomConnection(filename, mode, validate=validate)
>   File "/home/luna.kuleuven.be/u0124158/.local/lib/python3.6/site-packages/loompy/loompy.py", line 84, in __init__
>     self._file = h5py.File(filename, mode)
>   File "/home/luna.kuleuven.be/u0124158/.local/lib/python3.6/site-packages/h5py/_hl/files.py", line 427, in __init__
>     swmr=swmr)
>   File "/home/luna.kuleuven.be/u0124158/.local/lib/python3.6/site-packages/h5py/_hl/files.py", line 190, in make_fid
>     fid = h5f.open(name, flags, fapl=fapl)
>   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
>   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
>   File "h5py/h5f.pyx", line 96, in h5py.h5f.open
> OSError: Unable to open file (file signature not found)
> 
My OS is Ubuntu 18.0.4.5 LTS.

Any tips on how to solve this issue? 
Thank you very much in advance!

Best,
Tim

**Comment by cflerin** [comment]
Hi @HerpelinckT ,

Is it possible that you have an open connection to the same loom file in another process? In a notebook perhaps? You would need to close that before running this cli command (`lf.close()`).

**Comment by HerpelinckT** [comment]
Hi @cflerin 

Thank you very much for your fast response! `lf.close()` did the trick!
