### ISSUE TITLE
ValueError: Intersection of gene_names and tf_names is empty.

### ISSUE THREAD

**Issue by agarmill** [aertslab/SCENICprotocol#47]
Hello, 

Thank you for this resource! I am running the PBMC10k_SCENIC-protocol-CLI.ipynb protocol, and when I run SCENIC Steps phase 1a, I get an error. 

!pyscenic grn {f_loom_path_scenic} {f_tfs} -o adj.csv --num_workers 20
ValueError: Intersection of gene_names and tf_names is empty.

I have tried transposing the original matrix (as as is suggested in another issues post) but I still get the same error. 
Is there another reason I could be getting this error?

Thank you!

**Comment by cflerin** [comment]
```
Intersection of gene_names and tf_names is empty
```
A common cause is for this is using different gene symbols for the TFs vs expression matrix. This is what I would check first (along with possibly transposing the expr matrix).
