### ISSUE TITLE
Would it be better to use raw/normalized/batch-effect-removed input count matrix?

### ISSUE THREAD

**Issue by hongyaz** [aertslab/SCENICprotocol#52]
Hi,

Thank you for the cool software! I noticed that the pipeline in your Nature Protocol paper used raw counts as input of the pySCENIC software. I'm wondering if it is better to use raw, normalized or batch effect removed matrix, or it doesn't matter (they would perhaps produce similar results)?

Thanks again!
H

**Comment by SeppeDeWinter** [comment]
Hi @hongyaz 

It is fine to use raw gene expression counts, also see this issue: https://github.com/aertslab/pySCENIC/issues/20. But of course feel free to experiment with the input and look at the effect on the output. Results will probably be fairly similar. 

Best,

Seppe

**Comment by SeppeDeWinter** [comment]
Closing the issue for now, feel free to reopen if you have further issues.
