### ISSUE TITLE
Protocol

### ISSUE THREAD

**Issue by StevenTur** [aertslab/SCENICprotocol#65]
Hi, I am Steven, 

Thank you for your work, I have issues concerning the link for the protocol :

https://github.com/aertslab/SCENICprotocol/blob/master/notebooks/PBMC10k_SCENIC-protocol-CLI.ipynb

![Screen Shot 2022-09-22 at 1 00 35 PM](https://user-images.githubusercontent.com/106545864/191808973-2431fac7-9d38-4ace-abab-7a17c032ce7b.png)

The code doesn't appear.

Cordially,

Steven

**Comment by SeppeDeWinter** [comment]
Hi Steven

Often refreshing the browser does the trick.

If that does not work you can also download the ipynb file and open it in an application which can visualize jupyter notebooks (e.g. vscode, jupyterlab, ...)

There is also an html render of the notebook which you can download and open in a webbrowser: https://github.com/aertslab/SCENICprotocol/blob/master/notebooks/PBMC10k_SCENIC-protocol-CLI.html

Hope this helps.

Best

Seppe
