### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'object'.

### ISSUE THREAD

**Issue by Sparsh3101** [aertslab/SCENICprotocol#84]
I am trying to setup pyscenic, and getting this on pyscenic -h:

AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. 
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'object_'?

I also tried to create the environment with python 3.9 and numpy 1.20, but then I'm getting this error:

import pandas._libs.window.aggregations as window_aggregations
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /data/leuven/359/vsc35916/min
iconda3/envs/scenic_protocol/lib/python3.8/site-packages/pandas/_libs/window/aggregations.cpython-38-x86_64-linux
-gnu.so)

**Comment by wuxiangning** [comment]
hello!Could u tell us how to solve this problem!pls

**Comment by Sparsh3101** [comment]
> hello!Could u tell us how to solve this problem!pls

Hi @wuxiangning. They have corrected this issue in the recent commits. Installing with pip installs an older version. If you install the latest through github as described on the website it will work.

**Comment by wuxiangning** [comment]
hi, I solve this problem by changing my transform.py in envirmental: take the "np.object" to "object". it run good!

**Comment by wuxiangning** [comment]
I did see the older version of pyscenic installation,could u please give a HTML or code ? Thanks!
